# When training on natural language data such as reviews, tweets, and conversations

# If training data contains multiple columns, specify the column containing natural language text
# using the column_name parameter

schema_version: "1.0"
name: "natural-language-gpt"
models:
  - gpt_x:
      pretrained_model: "gretelai/gpt-auto"
      prompt_template: null
      column_name: null
      validation: null
      params:
        batch_size: 4
        epochs: null
        steps: 750
        weight_decay: 0.01
        warmup_steps: 100
        lr_scheduler: "linear"
        learning_rate: 0.0001
        max_tokens: 512
        gradient_accumulation_steps: 8
      peft_params:
        lora_r: 8
        lora_alpha_over_r: 1.0
        target_modules: null
      privacy_params:
        dp: false
        epsilon: 8.0
        delta: "auto"
        per_sample_max_grad_norm: 1.0
        entity_column_name: null
      generate:
        num_records: 80
        seed_records_multiplier: 1
        maximum_text_length: 100
        top_p: 0.8987601335810778
        top_k: 43
        num_beams: 1
        do_sample: true
        do_early_stopping: true
        typical_p: 0.8
        temperature: null
